# -*- coding: utf-8 -*-
"""Loss_Function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rNiGDUFaHuNtA0e4JXL3mDhyZF6i6h-Y
"""

# Loss functions (L1 + Perceptual (LPIPS) + SSIM)
import lpips
from pytorch_msssim import ssim

lpips_model = lpips.LPIPS(net='vgg').to(device)
lpips_model.eval()  # doesn't train

l1_loss = nn.L1Loss()

def compute_loss(output, target, alpha_lpips=0.05, alpha_ssim=0.4):
    # L1
    loss_l1 = l1_loss(output, target)
    # LPIPS expects [-1,1]
    out_lp = (output * 2.0) - 1.0
    tgt_lp = (target * 2.0) - 1.0
    loss_perc = lpips_model(out_lp, tgt_lp).mean()
    # SSIM (pytorch_msssim) returns value in [0,1], we want loss = 1 - ssim
    loss_ssim = 1.0 - ssim(output, target, data_range=1.0, size_average=True)
    total = loss_l1 + alpha_lpips * loss_perc + alpha_ssim * loss_ssim
    return total, loss_l1.item(), loss_perc.item(), loss_ssim.item()
