# -*- coding: utf-8 -*-
"""Gated Autoencoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1buEvaT5RKgZHVS0XWeaxj9KUoOWB2GqI
"""

# Gated Convolution layer (implementation)
class GatedConv2d(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1, dilation=1):
        super().__init__()
        # feature conv
        self.conv_feat = nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding, dilation=dilation)
        # gating conv (outputs gate map)
        self.conv_mask = nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding, dilation=dilation)
        self.activation = nn.ELU()  # can use ReLU or ELU

    def forward(self, x):
        feat = self.conv_feat(x)
        gate = self.conv_mask(x)
        gate = torch.sigmoid(gate)
        out = self.activation(feat) * gate
        return out

# Gated Autoencoder
class GatedAutoencoder(nn.Module):
    def __init__(self, latent_dim=256):
        super().__init__()
        # Encoder: reduce to latent feature map
        self.enc1 = GatedConv2d(3, 64, 4, 2, 1)     # 128->64
        self.enc2 = GatedConv2d(64, 128, 4, 2, 1)   # 64->32
        self.enc3 = GatedConv2d(128, 256, 4, 2, 1)  # 32->16
        self.enc4 = GatedConv2d(256, latent_dim, 4, 2, 1) # 16->8

        # Optional bottleneck conv to compress spatially
        # Decoder: upsample via ConvTranspose
        self.dec1 = nn.ConvTranspose2d(latent_dim, 256, 4, 2, 1) # 8->16
        self.dec1_g = nn.Sequential(nn.BatchNorm2d(256), nn.ReLU(True))
        self.dec2 = nn.ConvTranspose2d(256, 128, 4, 2, 1)        # 16->32
        self.dec2_g = nn.Sequential(nn.BatchNorm2d(128), nn.ReLU(True))
        self.dec3 = nn.ConvTranspose2d(128, 64, 4, 2, 1)         # 32->64
        self.dec3_g = nn.Sequential(nn.BatchNorm2d(64), nn.ReLU(True))
        self.dec4 = nn.ConvTranspose2d(64, 3, 4, 2, 1)           # 64->128

        self.output_act = nn.Sigmoid()

    def encode(self, x):
        x = self.enc1(x)
        x = self.enc2(x)
        x = self.enc3(x)
        latent = self.enc4(x)
        return latent

    def decode(self, z):
        x = self.dec1(z); x = self.dec1_g(x)
        x = self.dec2(x); x = self.dec2_g(x)
        x = self.dec3(x); x = self.dec3_g(x)
        x = self.dec4(x)
        x = self.output_act(x)
        return x

    def forward(self, x):
        z = self.encode(x)
        out = self.decode(z)
        return out, z